/**
 * configure-env.js
 *
 * Reads ANGULAR_API_URL from the environment and writes it into
 * environment.prod.ts before the Angular production build runs.
 *
 * Usage (automatic via npm prebuild):
 *   npm run build               ← triggers this script first
 *
 * Or manually:
 *   ANGULAR_API_URL=https://api.example.com/api/v1 node configure-env.js
 */

const fs = require('fs');
const path = require('path');

const apiUrl     = process.env.ANGULAR_API_URL || 'http://localhost:8080/api/v1';
const backendUrl = new URL(apiUrl).origin;

const content = `// Auto-generated by configure-env.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  backendUrl: '${backendUrl}',
};
`;

const targetPath = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(targetPath, content, 'utf8');

console.log(`[configure-env] environment.prod.ts → apiUrl: ${apiUrl} | backendUrl: ${backendUrl}`);
